;;; visual.scm - Visual mode operators and selection

(define (vim-visual-range)
  (let* ((anchor (%mark-position #\<))
         (point (point-get))
         (sel-min (min anchor point))
         (sel-max (max anchor point))
         (mode (%select-mode-get)))
    (case mode
      ((1) ;; char: inclusive of both ends
       (make-range sel-min (+ sel-max (utf8-byte-len-at sel-max)) 'char))
      ((2) ;; line: expand to full line boundaries
       (let* ((line-min (%position-line sel-min))
              (line-max (%position-line sel-max))
              (start (%line-start-position line-min))
              (end (%line-end-position line-max)))
         (make-range start end 'line))))))

;; Returns line-end position exclusive of any trailing newline.
(define (line-content-end line)
  (let ((le (%line-end-position line)))
    (if (and (> le 0) (char=? (char-at (- le 1)) #\newline))
        (- le 1)
        le)))

(define (vim-rect-bounds)
  (let* ((anchor (%mark-position #\<))
         (point  (point-get))
         (la (%position-line anchor))
         (lb (%position-line point))
         (ca (- anchor (%line-start-position la)))
         (cb (- point  (%line-start-position lb))))
    (list (min la lb) (max la lb) (min ca cb) (+ (max ca cb) 1))))

(define (vim-visual-rect-insert)
  (let* ((b (vim-rect-bounds))
         (row-min (list-ref b 0)) (row-max (list-ref b 1))
         (col-min (list-ref b 2)))
    (%begin-change)
    (set! vim-rect-insert-info (list row-min row-max col-min #f))
    (set! vim-pending-repeat-info
      (make-repeat-info 'op-rect-insert 1 #f #f #f #f 'rect-insert #f))
    (point-set! (min (+ (%line-start-position row-min) col-min)
                     (%line-end-position row-min)))
    (vim-insert)))

(define (vim-visual-rect-append)
  (let* ((b (vim-rect-bounds))
         (row-min (list-ref b 0)) (row-max (list-ref b 1))
         (col-max (list-ref b 3))
         (ragged? (= (%select-mode-get) 4)))
    (%begin-change)
    (set! vim-rect-insert-info (list row-min row-max col-max ragged?))
    (set! vim-pending-repeat-info
      (make-repeat-info 'op-rect-append 1 #f #f #f #f 'rect-append #f))
    (point-set! (if ragged?
                    (line-content-end row-min)
                    (min (+ (%line-start-position row-min) col-max)
                         (%line-end-position row-min))))
    (vim-insert)))

(define (vim-rect-apply op . rest)
  (let* ((ragged? (and (not (null? rest)) (car rest)))
         (anchor (%mark-position #\<))
         (point (point-get))
         (line-a (%position-line anchor))
         (line-b (%position-line point))
         (row-min (min line-a line-b))
         (row-max (max line-a line-b))
         (col-a (- anchor (%line-start-position line-a)))
         (col-b (- point (%line-start-position line-b)))
         (col-min (min col-a col-b))
         (col-max (+ (max col-a col-b) 1)))
    ;; iterate bottom to top so deletions don't shift lines above
    (let loop ((line row-max))
      (when (>= line row-min)
        (let* ((ls (%line-start-position line))
               (content-end (if ragged? (line-content-end line) (%line-end-position line)))
               (start (+ ls col-min))
               (end (if ragged? content-end (min (+ ls col-max) content-end))))
          (when (and (<= start content-end) (> end start))
            (op start end)))
        (loop (- line 1))))
    ;; cursor to upper-left corner
    (let ((ls (%line-start-position row-min)))
      (point-set! (min (+ ls col-min)
                       (%line-end-position row-min))))))

(define (vim-visual-delete)
  (%begin-change)
  (let ((mode (%select-mode-get)))
    (if (rect-mode? mode)
        (let* ((anchor (%mark-position #\<))
               (cur-point (point-get))
               (line-a (%position-line anchor))
               (line-b (%position-line cur-point))
               (row-min (min line-a line-b))
               (row-max (max line-a line-b))
               (col-a (- anchor (%line-start-position line-a)))
               (col-b (- cur-point (%line-start-position line-b)))
               (col-min (min col-a col-b))
               (col-max (+ (max col-a col-b) 1))
               (ragged? (= mode 4))
               (width (- col-max col-min)))
          (let collect ((line row-min) (parts '()))
            (if (> line row-max)
                (let* ((text (string-join-newlines (reverse parts)))
                       (saved-reg current-vim-register))
                  (vim-register-write! text 'blockwise)
                  (let ((actual (if (char-upper-case? saved-reg)
                                    (char-downcase saved-reg)
                                    saved-reg)))
                    (%register-set-block-width! actual width)
                    (when (not (char=? actual #\"))
                      (%register-set-block-width! #\" width))))
                (let* ((ls (%line-start-position line))
                       (le (%line-end-position line))
                       (start (+ ls col-min))
                       (end   (if ragged? (line-content-end line) (min (+ ls col-max) le)))
                       (chunk (if (<= start le)
                                  (%buffer-substring start end)
                                  "")))
                  (collect (+ line 1) (cons chunk parts)))))
          (vim-rect-apply delete-range ragged?))
        (let* ((shape (if (= mode 2) 'linewise 'charwise))
               (range (vim-visual-range)))
          (let* ((start (range-start range))
                 (end   (range-end range))
                 (text  (%buffer-substring start end))
                 ;; Linewise delete on the last line (no trailing newline): include
                 ;; the preceding newline so the empty line doesn't remain.
                 (start (if (and (= mode 2)
                                 (= end (buffer-length))
                                 (> start 0)
                                 (char=? (char-at (- start 1)) #\newline))
                            (- start 1)
                            start)))
            (vim-register-write! text shape)
            (point-set! start)
            (delete-range start end)))))
  (%change-set-repeat-info!
    (make-repeat-info 'op-delete 1 #f #f
                      vim-last-visual-text-object
                      vim-last-visual-text-object-kind #f #f))
  (%end-change)
  (vim-normal))

(define (vim-visual-change)
  (%begin-change)
  (set! vim-pending-repeat-info
    (make-repeat-info 'op-change 1 #f #f
                      vim-last-visual-text-object
                      vim-last-visual-text-object-kind #f #f))
  (let ((mode (%select-mode-get)))
    (if (rect-mode? mode)
        ;; rectangle: delete rect, enter insert at upper-left
        (let* ((b (vim-rect-bounds))
               (row-min (list-ref b 0)) (row-max (list-ref b 1))
               (col-min (list-ref b 2))
               (ragged? (= mode 4)))
          (set! vim-rect-insert-info (list row-min row-max col-min #f))
          (vim-rect-apply delete-range ragged?)
          (vim-insert))
        ;; char or line
        (let ((range (vim-visual-range)))
          (let* ((start (range-start range))
                 (end (range-end range))
                 ;; for line mode: strip trailing newline so we stay on same line
                 (end (if (and (eq? (range-type range) 'line)
                               (> end start)
                               (char=? (char-at (- end 1)) #\newline))
                          (- end 1) end)))
            (point-set! start)
            (delete-range start end)
            (vim-insert))))))

(define (vim-visual-yank)
  (let* ((mode (%select-mode-get))
         (anchor (%mark-position #\<))
         (cur-point (point-get))
         (sel-min (min anchor cur-point)))
    (if (rect-mode? mode)
        ;; block mode: collect per-line content within the rectangle
        (let* ((line-a (%position-line anchor))
               (line-b (%position-line cur-point))
               (row-min (min line-a line-b))
               (row-max (max line-a line-b))
               (col-a (- anchor (%line-start-position line-a)))
               (col-b (- cur-point (%line-start-position line-b)))
               (col-min (min col-a col-b))
               (col-max (+ (max col-a col-b) 1))
               (ragged? (= mode 4))
               (width (- col-max col-min)))
          (let collect ((line row-min) (parts '()))
            (if (> line row-max)
                (let* ((text (string-join-newlines (reverse parts)))
                       (saved-reg current-vim-register))
                  (vim-register-write! text 'blockwise)
                  (let ((actual (if (char-upper-case? saved-reg)
                                    (char-downcase saved-reg)
                                    saved-reg)))
                    (%register-set-block-width! actual width)
                    (when (not (char=? actual #\"))
                      (%register-set-block-width! #\" width))))
                (let* ((ls (%line-start-position line))
                       (le (%line-end-position line))
                       (start (+ ls col-min))
                       (end   (if ragged? (line-content-end line) (min (+ ls col-max) le)))
                       (chunk (if (<= start le)
                                  (%buffer-substring start end)
                                  "")))
                  (collect (+ line 1) (cons chunk parts))))))
        (let ((range (vim-visual-range)))
          (vim-register-write!
            (%buffer-substring (range-start range) (range-end range))
            (if (= mode 2) 'linewise 'charwise))))
    (point-set! sel-min)
    (vim-normal)))

(define (vim-visual-paste)
  (let* ((reg current-vim-register)
         (text (if (char=? reg #\+)
                   (let ((s (%clipboard-get)))
                     (if (string=? s "") #f s))
                   (%register-get reg)))
         (shape (if (char=? reg #\+) 'charwise (%register-shape reg))))
    (when text
      (%begin-change)
      (let ((mode (%select-mode-get)))
        (if (rect-mode? mode)
            (let* ((b (vim-rect-bounds))
                   (row-min (list-ref b 0))
                   (row-max (list-ref b 1))
                   (col-min (list-ref b 2))
                   (col-max (list-ref b 3))
                   (ragged? (= mode 4))
                   (paste-lines (string-split-newlines text)))
              ;; Collect deleted content top-to-bottom for register swap
              (let collect ((line row-min) (parts '()))
                (if (> line row-max)
                    (vim-register-write! (string-join-newlines (reverse parts)) 'blockwise)
                    (let* ((ls (%line-start-position line))
                           (le (%line-end-position line))
                           (start (+ ls col-min))
                           (end (if ragged? (line-content-end line) (min (+ ls col-max) le)))
                           (chunk (if (<= start le) (%buffer-substring start end) "")))
                      (collect (+ line 1) (cons chunk parts)))))
              ;; Delete selected columns and insert paste line, bottom-to-top
              (let loop ((row row-max))
                (when (>= row row-min)
                  (let* ((i (- row row-min))
                         (ls (%line-start-position row))
                         (le (%line-end-position row))
                         (content-end (if ragged? (line-content-end row) le))
                         (del-start (+ ls col-min))
                         (del-end (if ragged? content-end (min (+ ls col-max) content-end))))
                    (when (and (<= del-start content-end) (> del-end del-start))
                      (delete-range del-start del-end))
                    (let ((chunk (list-ref paste-lines (modulo i (length paste-lines)))))
                      (when (not (string=? chunk ""))
                        (let* ((ls2 (%line-start-position row))
                               (ins (min (+ ls2 col-min) (%line-end-position row))))
                          (point-set! ins)
                          (%insert-string chunk)))))
                  (loop (- row 1))))
              ;; Leave cursor at upper-left of rect
              (point-set! (min (+ (%line-start-position row-min) col-min)
                               (%line-end-position row-min))))
            ;; Char/line: delete selection, paste in place
            (let* ((shape-out (if (= mode 2) 'linewise 'charwise))
                   (range (vim-visual-range))
                   (r-start (range-start range))
                   (r-end   (range-end range))
                   (deleted (%buffer-substring r-start r-end))
                   (del-start (if (and (= mode 2)
                                       (= r-end (buffer-length))
                                       (> r-start 0)
                                       (char=? (char-at (- r-start 1)) #\newline))
                                  (- r-start 1)
                                  r-start)))
              (vim-register-write! deleted shape-out)
              (point-set! del-start)
              (delete-range del-start r-end)
              (cond
                ((eq? shape 'blockwise)
                 (let* ((cur-line (%position-line (point-get)))
                        (cur-ls   (%line-start-position cur-line))
                        (col      (- (point-get) cur-ls))
                        (lines    (string-split-newlines text)))
                   (vim-paste-block lines col)
                   (point-set! (+ (%line-start-position cur-line) col))))
                ((eq? shape 'linewise)
                 (let ((stripped (strip-trailing-newline text)))
                   (line-start)
                   (let ((paste-start (point-get)))
                     (%insert-string stripped)
                     (%insert-string "\n")
                     (point-set! paste-start))))
                (else
                 (let ((paste-start (point-get)))
                   (%insert-string text)
                   (point-set! paste-start)))))))
      (%end-change)))
  (set! current-vim-register #\")
  (vim-normal))

;;;
;;; Linewise-force helper (used by vim-D and vim-X in visual mode)
;;;

;; Delete all lines spanned by the current visual selection, regardless of select mode.
(define (vim-visual-force-linewise-delete)
  (%begin-change)
  (let* ((anchor (%mark-position #\<))
         (cur-point (point-get))
         (line-min (%position-line (min anchor cur-point)))
         (line-max (%position-line (max anchor cur-point)))
         (start (%line-start-position line-min))
         (end   (%line-end-position line-max))
         (text  (%buffer-substring start end))
         ;; On the last line of the buffer there may be no trailing newline:
         ;; include the preceding newline instead so no empty line is left behind.
         (start (if (and (= end (buffer-length))
                         (> start 0)
                         (char=? (char-at (- start 1)) #\newline))
                    (- start 1)
                    start)))
    (vim-register-write! text 'linewise)
    (point-set! start)
    (delete-range start end))
  (%change-set-repeat-info!
    (make-repeat-info 'op-delete 1 #f #f
                      vim-last-visual-text-object
                      vim-last-visual-text-object-kind #f #f))
  (%end-change)
  (vim-normal))

;;;
;;; Mode-aware commands (normal + visual dispatch)
;;;

(defcommand (vim-A)
  "vim: append to line or selection\nIn normal mode, move to end of line and enter insert mode.\nIn visual mode, enter insert mode at the right column of each line in the rectangle."
  (if (> (%select-mode-get) 0)
      (vim-visual-rect-append)
      (append-line)))

(defcommand (vim-I)
  "vim: insert at line start or selection\nIn normal mode, move to first non-blank and enter insert mode.\nIn visual mode, enter insert mode at the left column of each line in the rectangle."
  (if (> (%select-mode-get) 0)
      (vim-visual-rect-insert)
      (insert-at-start)))

(defcommand (vim-d)
  "vim: delete operator or selection\nIn normal mode, enter operator-pending state; combine with a motion to delete.\nIn visual mode, delete the selection."
  (unless (buffer-read-only?)
    (if (> (%select-mode-get) 0)
        (vim-visual-delete)
        (vim-op-delete))))

(defcommand (vim-c)
  "vim: change operator or selection\nIn normal mode, enter operator-pending state; combine with a motion to change.\nIn visual mode, delete the selection and enter insert mode."
  (unless (buffer-read-only?)
    (if (> (%select-mode-get) 0)
        (vim-visual-change)
        (vim-op-change))))

(defcommand (vim-y)
  "vim: yank operator or selection\nIn normal mode, enter operator-pending state; combine with a motion to yank.\nIn visual mode, yank the selection."
  (if (> (%select-mode-get) 0)
      (vim-visual-yank)
      (vim-op-yank)))

(defcommand (vim-x)
  "vim: delete character or selection\nIn normal mode, delete character(s) forward.\nIn visual mode, delete the selection."
  (unless (buffer-read-only?)
    (if (> (%select-mode-get) 0)
        (vim-visual-delete)
        (vim-x-impl))))

(defcommand (vim-p)
  "vim: paste after cursor or into selection\nIn normal mode, paste register contents after the cursor.\nIn visual mode, paste register contents replacing the selection."
  (unless (buffer-read-only?)
    (if (> (%select-mode-get) 0)
        (vim-visual-paste)
        (vim-paste-after))))

(defcommand (vim-P)
  "vim: paste before cursor or into selection\nIn normal mode, paste register contents before the cursor.\nIn visual mode, paste register contents replacing the selection."
  (unless (buffer-read-only?)
    (if (> (%select-mode-get) 0)
        (vim-visual-paste)
        (vim-paste-before))))

;; Visual mode operator bindings
(set-key! select-map "d" 'vim-d)
(set-key! select-map "x" 'vim-x)
(set-key! select-map "c" 'vim-c)
(set-key! select-map "s" 'vim-c)
(set-key! select-map "D" 'vim-D)
(set-key! select-map "C" 'vim-c)
(set-key! select-map "S" 'vim-S)
(set-key! select-map "X" 'vim-X)
(set-key! select-map "y" 'vim-y)
(set-key! select-map "I" 'vim-I)
(set-key! select-map "A" 'vim-A)
(set-key! select-map "p" 'vim-p)
(set-key! select-map "P" 'vim-P)

;; Visual mode motion bindings
(set-key! select-map "w" 'vim-motion-w)
(set-key! select-map "b" 'vim-motion-b)
(set-key! select-map "e" 'vim-motion-e)
(set-key! select-map "W" 'vim-motion-W)
(set-key! select-map "B" 'vim-motion-B)
(set-key! select-map "E" 'vim-motion-E)
(set-key! select-map "%" 'vim-motion-%)
(set-key! select-map "g g" 'vim-motion-gg)
(set-key! select-map "G" 'vim-motion-G)

;; Visual mode search bindings — reuses normal-mode search commands so
;; the search bar (and n/N navigation) can be reached without leaving
;; visual mode and clearing the selection.
(set-key! select-map "/" 'vim-search-open)
(set-key! select-map "?" 'vim-search-open-backward)
(set-key! select-map "n" 'vim-search-next)
(set-key! select-map "N" 'vim-search-prev)
